/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '출석률': RouteRecordInfo<
      '출석률',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'not-found': RouteRecordInfo<
      'not-found',
      '/:pathMatch(.*)*',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'attendance': RouteRecordInfo<
      'attendance',
      '/admin/attendance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'birthday': RouteRecordInfo<
      'birthday',
      '/admin/birthday',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'car': RouteRecordInfo<
      'car',
      '/admin/car',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dues': RouteRecordInfo<
      'dues',
      '/admin/dues',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'members': RouteRecordInfo<
      'members',
      '/admin/members',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'officers': RouteRecordInfo<
      'officers',
      '/admin/officers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'stat': RouteRecordInfo<
      'stat',
      '/admin/stat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'edit': RouteRecordInfo<
      'edit',
      '/edit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'etc': RouteRecordInfo<
      'etc',
      '/etc',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'history': RouteRecordInfo<
      'history',
      '/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'practice': RouteRecordInfo<
      'practice',
      '/practice',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'seat': RouteRecordInfo<
      'seat',
      '/seat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'status': RouteRecordInfo<
      'status',
      '/status',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/index.vue': {
      routes:
        | '출석률'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/ErrorNotFound.vue': {
      routes:
        | 'not-found'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/admin/attendance.vue': {
      routes:
        | 'attendance'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/admin/birthday.vue': {
      routes:
        | 'birthday'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/admin/car.vue': {
      routes:
        | 'car'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/admin/dues.vue': {
      routes:
        | 'dues'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/admin/members/index.vue': {
      routes:
        | 'members'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/admin/officers/index.vue': {
      routes:
        | 'officers'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/admin/stat.vue': {
      routes:
        | 'stat'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/edit/index.vue': {
      routes:
        | 'edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/etc/index.vue': {
      routes:
        | 'etc'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/history/index.vue': {
      routes:
        | 'history'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/practice.vue': {
      routes:
        | 'practice'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/seat.vue': {
      routes:
        | 'seat'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/status/index.vue': {
      routes:
        | 'status'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
